config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resources :tasks
  root 'tasks#index'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  namespace :admin do
  	resources :users
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/label.rb
class Label < ApplicationRecord
end

app/models/task.rb
# frozen_string_literal: true

class Task < ApplicationRecord
  belongs_to :user
  validates :task_name, presence: true
  validates :details, length: { maximum: 255 }

  enum status: { waiting: 0, working: 1, completed: 2 }
  scope :status_sorted, ->(status) { where(status: status) if status.present? }
end

app/models/tasklabel.rb
class Tasklabel < ApplicationRecord
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :tasks, dependent: :destroy
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, on: :create
  validates :name, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, presence: true,
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
		def index
			@users = User.all
		end

		def new
			@user = User.new
		end

		def create
			@user = User.new(user_params)
			if @user.save
				redirect_to admin_users_path
			else
				render :new
			end
		end

		def show
			@user = User.find(params[:id])
			@tasks = @user.tasks.order(id: "DESC")
		end

		def edit
			@user = User.find(params[:id])
		end

		def update
			@user = User.find(params[:id])
			if @user.update(user_params)
				flash[:success] = "更新されました"
				redirect_to edit_admin_user_path(@user)
			end
			flash[:danger] = "保存が失敗しました"
			render :edit
		end

		def destroy
			@user = User.find(params[:id])
			@user.destroy
			redirect_to admin_users_path
		end

		def user_params
    params.require(:user).permit(:name,
                                 :email,
                                 :password
                                 )
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  before_action :login_done, only: %i[new create]
  def new; end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user&.authenticate(params[:session][:password])
      log_in user
      redirect_to root_path
    else
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_path
  end
end

app/controllers/tasks_controller.rb
# frozen_string_literal: true

class TasksController < ApplicationController
  before_action :authenticate_user!
  def index
    @tasks = if params[:search]
               Task.where('task_name LIKE ?', "%#{params[:search]}%").page(params[:page]).per(3)
             elsif params[:deadline].to_i == 1
               Task.order(deadline_at: 'DESC').page(params[:page]).per(3)
             elsif params[:deadline].to_i == 2
               Task.order(deadline_at: 'ASC').page(params[:page]).per(3)
             elsif params[:status]
               Task.status_sorted(params[:status]).page(params[:page]).per(3)
             else
               Task.page(params[:page]).per(3).reverse_order
             end
    @d = params[:deadline]
    @s = params[:status]
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.user_id = current_user.id
    if @task.save
      redirect_to @task
    else
      render :new
    end
  end

  def show
    @task = Task.find(params[:id])
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    task = Task.find(params[:id])
    task.update(task_params)
    redirect_to task_path(task.id)
  end

  def destroy
    task = Task.find(params[:id])
    task.destroy
    redirect_to root_path
  end

  private

  def task_params
    params.require(:task).permit(:task_name,
                                 :details,
                                 :deadline_at,
                                 :status)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]
  before_action :login_done, only: %i[new create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @tasks = @user.tasks
  end

  private

  def user_params
    params.require(:user).permit(:name,
                                 :email,
                                 :password)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def authenticate_user!
    redirect_to login_path unless logged_in?
  end

  def login_done
    redirect_to root_path if logged_in?
  end
end

app/helpers/tasks_helper.rb
# frozen_string_literal: true

module TasksHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="flash">
	<% if flash[:success] %>
		<p class="success"><%= flash[:success] %></p>
	<% else %>
	 <p class="danger"><%= flash[:danger] %></p>
	<% end %>
</div>

<%= form_for(@user,url: admin_user_path) do |f| %>
	<%= f.text_field :name %>
	<%= f.email_field :email %>

	<%= f.submit "編集" %>
<% end %>

<%= link_to "ユーザー削除", admin_user_path(@user), method: :delete, data: { confirm: "本当に削除しますか？" } %>

app/views/admin/users/index.html.erb
<table class="table table-bordered">
	<thead>
		<tr>
			<th>名前</th>
			<th>メールアドレス</th>
			<th>タスク</th>
			<th>タスク数</th>
			<th>編集</th>
		</tr>
	</thead>
	<tbody>
		<% @users.each do |user| %>
		<tr>
			<td><%= user.name %></td>
			<td><%= user.email %></td>
			<td><%= link_to "タスク確認", admin_user_path(user) %></td>
			<td>タスク数：<%= user.tasks.count %></td>
			<td><%= link_to "ユーザー情報編集", edit_admin_user_path(user) %></td>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/admin/users/new.html.erb
<div class="container">
	<div class="row">
		<div class="center">
			<h3>ユーザー作成</h3>
			<%= form_for @user, url: admin_users_path do |f| %>
				<%= render 'users/user_error_messages', user: @user %>
				<p><%= f.label :name %></p>
				<p><%= f.text_field :name %></p>
				<p><%= f.label :email %></p>
				<p><%= f.email_field :email %></p>
				<p><%= f.label :password%></p>
				<p><%= f.password_field :password %></p>
				<%= f.submit "New user" %>
			<% end %>
		</div>
	</div>
</div>

app/views/admin/users/show.html.erb
<h3><%= @user.name %>のタスク</h3>
<table class="table table-bordered">
	<thead>
		<tr>
			<th>タスク名</th>
			<th>詳細</th>
			 <th>
			 	<%= form_tag(tasks_path, method: :get) do %>
			 		<%= select_tag :deadline, options_for_select({"期限：新しい順" => 1, "期限：古い順" => 2}, :selected => @d), id: 'deadline', prompt: '-' %>
					<%= submit_tag 'sort' %>
				<% end %>
			</th>
			<th><%= form_tag(tasks_path, method: :get) do %>
					<%= select_tag :status, options_for_select({"waiting" => "waiting", "working" => "working", "completed" => "completed"}, :selected => @s), id: 'status', prompt: '-' %>
					<%= submit_tag 'status' %>
				<% end %>
			</th>
			<th></th>

		</tr>
	</thead>
	<% @tasks.each do |task| %>
	<tbody>
		<tr>
			<td><%= task.task_name %></td>
			<td><%= task.details %></td>
			<td><%= task.deadline_at.strftime('%Y/%m/%d') %></td>
			<td><%= task.status %></td>
			<td>
				<%= link_to 'show', task_path(task.id) %>
				<%= link_to 'edit', edit_task_path(task.id) %>
				<%= link_to 'destory', task_path(task.id), method: :delete %>
			</td>
		</tr>
	</tbody>
	<% end %>
</table>

app/views/layouts/_error_messages.html.erb
<% if task.errors.any? %>
  <div id="error_explanation">
    <h4><%= task.errors.count %>件のエラーがあります。</h4>
    <ul>
    <% task.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav>
        <ul>
        <% if logged_in? %>
          <li><%= link_to "Home", root_path,class: "nav_item" %></li>
          <li><%= link_to "My Task", user_path(@current_user),class: "nav_item" %></li>
          <li><%= link_to "New", new_task_path,class: "nav_item" %></li>
          <li><%= link_to "Log out", logout_path, method: :delete, class: "nav_item" %></li>
        <% else %>
          <li><%= link_to "Sign up", new_user_path %></li>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
        </ul>
      </nav>
    </header>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<div class="container">
	<div class="row">
		<div class="center">
			<h3>Edit Task</h3>
			<%= form_for @task do |f| %>
				<p><%= f.label :task_name %></p>
				<p><%= f.text_field :task_name %></p>
				<p><%= f.label :details %></p>
				<p><%= f.text_area :details %></p>
				<p><%= f.label :deadline_at %></p>
				<p><%= f.select :status, Task.statuses.keys.to_a, {} %></p>
				<p><%= f.date_select :deadline_at %></p>
				<%= f.submit "編集" %>
			<% end %>
		</div>
	</div>
</div>

app/views/tasks/index.html.erb
<div>タスク名検索
	<%= form_tag(tasks_path, method: :get) do %>
	  <%= text_field_tag :search, params[:search] %>
	  <%= submit_tag 'Search', name: nil %>
	<% end %>
</div>


<table class="table table-bordered">
	<thead>
		<tr>
			<th>タスク名</th>
			<th>詳細</th>
			 <th>
			 	<%= form_tag(tasks_path, method: :get) do %>
			 		<%= select_tag :deadline, options_for_select({"期限：新しい順" => 1, "期限：古い順" => 2}, :selected => @d), id: 'deadline', prompt: '-' %>
					<%= submit_tag 'sort' %>
				<% end %>
			</th>
			<th><%= form_tag(tasks_path, method: :get) do %>
					<%= select_tag :status, options_for_select({"waiting" => "waiting", "working" => "working", "completed" => "completed"}, :selected => @s), id: 'status', prompt: '-' %>
					<%= submit_tag 'status' %>
				<% end %>
			</th>
			<th></th>

		</tr>
	</thead>
	<tbody>
	<% @tasks.each do |task| %>
		<tr>
			<td><%= task.task_name %></td>
			<td><%= task.details %></td>
			<td><%= task.deadline_at.strftime('%Y/%m/%d') %></td>
			<td><%= task.status %></td>
			<td>
				<%= link_to 'show', task_path(task.id) %>
				<%= link_to 'edit', edit_task_path(task.id) %>
				<%= link_to 'destory', task_path(task.id), method: :delete %>
			</td>
		</tr>
	<% end %>
	</tbody>
</table>
<%= paginate @tasks, class: "paginate" %>

app/views/tasks/new.html.erb
<div class="container">
	<div class="row">
		<div class="center">
			<h3>New Task</h3>
			<%= form_for @task do |f| %>
			  <%= render 'layouts/error_messages', task: @task %>
				<p><%= f.label :task_name %></p>
				<p><%= f.text_field :task_name %></p>
				<p><%= f.label :details %></p>
				<p><%= f.text_area :details, :placeholder => "max is 255 characters" %></p>
				<p><%= f.label :deadline_at %></p>
				<p><%= f.date_select :deadline_at %></p>
				<%= f.submit "タスク作成" %>
			<% end %>
		</div>
	</div>
</div>

app/views/tasks/show.html.erb
<div class="cotainer">
	<div class="row">
		<div class="center">
			<p>タスク名<%= @task.task_name %></p>
			<p>詳細<%= @task.details %></p>
			<p>ステータス<%= @task.status %></p>
			<p>締切日<%= @task.deadline_at.strftime('%Y/%m/%d') %></p>
			<%= link_to "edit", edit_task_path(@task.id) %>
			<%= link_to "home", root_path %>
		</div>
	</div>
</div>

app/views/users/_user_error_messages.html.erb
<% if user.errors.any? %>
  <div id="error_explanation">
    <h4><%= user.errors.count %>件のエラーがあります。</h4>
    <ul>
    <% user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/new.html.erb
<div class="container">
	<div class="row">
		<div class="center">
			<h3>Sign up</h3>
			<%= form_for @user, url: users_path do |f| %>
				<%= render 'users/user_error_messages', user: @user %>
				<p><%= f.label :name %></p>
				<p><%= f.text_field :name %></p>
				<p><%= f.label :email %></p>
				<p><%= f.email_field :email %></p>
				<p><%= f.label :password%></p>
				<p><%= f.password_field :password %></p>
				<%= f.submit "New user" %>
			<% end %>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<table class="table table-bordered">
	<thead>
		<tr>
			<th>タスク名</th>
			<th>詳細</th>
			 <th>
			 	<%= form_tag(tasks_path, method: :get) do %>
			 		<%= select_tag :deadline, options_for_select({"期限：新しい順" => 1, "期限：古い順" => 2}, :selected => @d), id: 'deadline', prompt: '-' %>
					<%= submit_tag 'sort' %>
				<% end %>
			</th>
			<th><%= form_tag(tasks_path, method: :get) do %>
					<%= select_tag :status, options_for_select({"waiting" => "waiting", "working" => "working", "completed" => "completed"}, :selected => @s), id: 'status', prompt: '-' %>
					<%= submit_tag 'status' %>
				<% end %>
			</th>
			<th></th>

		</tr>
	</thead>
	<% @tasks.each do |task| %>
	<tbody>
		<tr>
			<td><%= task.task_name %></td>
			<td><%= task.details %></td>
			<td><%= task.deadline_at.strftime('%Y/%m/%d') %></td>
			<td><%= task.status %></td>
			<td>
				<%= link_to 'show', task_path(task.id) %>
				<%= link_to 'edit', edit_task_path(task.id) %>
				<%= link_to 'destory', task_path(task.id), method: :delete %>
			</td>
		</tr>
	</tbody>
	<% end %>
</table>